version: "3.9"
services:
  minio:
      image: minio/minio
      command: [ "server", "--console-address", ":9001", "/data" ]
      restart: always
      ports:
          - "9000:9000"
          - "9001:9001"
      environment:
          MINIO_ROOT_USER: userminio
          MINIO_ROOT_PASSWORD: kiasu123
          MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
          MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      volumes:
          - "minio_data:/data"

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY;
      /usr/bin/mc rm -r --force myminio/asset;
      /usr/bin/mc mb myminio/asset;
      /usr/bin/mc policy download myminio/asset;
      exit 0;
      "
  service:
    build:
      context: .
      dockerfile: Dockerfile
    image: api
    restart: always
    environment:
      ENV: DEV
      PORT: 9001
      SSL: FALSE
      API_VERSION: 1.0
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_NAME: kredit_plus
      DB_USER: root
      DB_PASS:
      X_API_KEY: 030415fa-499b-49d7-95e6-c85382c46295
      INTEREST: 10
      ADMIN_FEE: 10
#    command: sh -c './scripts/wait-for db:5432 redis:6379 -- make run-watch && go test -v ./pkg/unit_testing'
    ports:
      - "8000:8000"
    extra_hosts:
      - "db:172.26.0.1"
volumes:
    minio_data:

